## 导包

In [36]:
import numpy as np

## 使用Numpy数组的优势

Numpy中数组的对象成为ndarray，意思是n维数组，一维数组：1-D。数组中所有元素都属于同一类型

In [37]:
one_d_arr = np.array([10,12])
print(one_d_arr)

[10 12]


## 创建Numpy数组

第一种方法，函数array创建一个1-D 数组，该函数将值列表作为参数并返回1-D 数组

In [38]:
a = np.array([1,2,3])
print(a)


[1 2 3]


第二种方法，np.arange()。返回给定区间内均匀分布的值数组。要了解有关此函数采用的参数的更多信息，Jupyter Notebook 中有一个强大的功能，您只需在函数后面单击按键盘上的 shift+tab 即可访问任何函数的文档。尝试一下 np.arange（） 的内置文档。

In [39]:
# 默认步长是1，不填入start默认从0开始，stop不包含
b = np.arange(3)
print(b)


[0 1 2]


In [40]:
c = np.arange(1,20,3)
print(c)

[ 1  4  7 10 13 16 19]


如果想创建一个在0到100的区间内具有五个均匀分布值的数组，函数必须采用3个参数，起始数字，最终数字和数组中的元素数。np.linspace()专门执行此操作

In [41]:
lin_spaced_arr = np.linspace(0,100,5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


当然，np.arange()也能实现

In [42]:
d = np.arange(0,101,25)
print(d)

[  0  25  50  75 100]


注意到np.linspace()函数的输出以浮点数的形式显示，原因是 NumPy 函数 np.linspace 中值的默认类型是浮点 （np.float64）。您可以使用 dtype 轻松指定数据类型。如果您访问函数的内置文档，您可能会注意到大多数函数都采用可选参数 dtype。除了 float 之外，NumPy 还有其他几种数据类型，例如 int 和 char

In [43]:
lin_spaced_arr = np.linspace(0,100,5,dtype =int)
print(lin_spaced_arr)

[  0  25  50  75 100]


In [44]:
c_int = np.arange(1,20,3,dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [45]:
b_float = np.arange(3,dtype=float)
print(b_float)

[0. 1. 2.]


In [46]:
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype)

['Welcome to Math for ML!']
<U23


你是否注意到 'char_arr' 数组的数据类型的输出是 '<U23'？
这意味着字符串（" 欢迎来到 Math for ML！''）是一个 23 个字符（23）的 unicode 字符串（'U'） (<). 您可以在 [此处]（https://docs.scipy.org/doc/NumPy-1.13.0/reference/arrays.dtypes.html）了解有关数据类型的更多信息。

## 有关Numpy数组的更多信息
使用numpy的优点之一是，可以使用内置函数轻松创建数组，例如：
* np.ones() - 返回一个新的数组，将值设为1.
* np.zeros() - 返回一个新的数组，将值设置为0
* np.empty() - 返回一个新的未初始化数组,其值也为0
* np.random.ran() -返回一个从0~1随机选择值的新数组



In [47]:
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [48]:
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [49]:
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [50]:
rand_arr = np.random.rand(3)
print(rand_arr)

[0.36621739 0.20637883 0.32231512]


## 多维数组
使用 NumPy，您还可以创建具有多个维度的数组。在上面的示例中，您处理了一维数组，您可以使用单个索引访问它们的元素。多维数组有多列。将多维数组视为 Excel 表格，其中每一行 / 每一列代表一个维度。 

In [51]:
two_dim_arr = np.array([[1,2,3],[4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


创建多维数组的另一种方法是重塑1-D数组，使用np.reshape()可以将前一个数组的元素重新排列成新形状

In [52]:
one_dim_arr = np.array([1,2,3,4,5,6])
multi_dim_arr = np.reshape(
                one_dim_arr, #要重塑的数组
                (2,3) #新数组的维度
                )
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


## 查找大小，形状和尺寸
在以后的作业中，您将需要知道如何找到数组的大小、维度和形状。这些都是ndarray的atributes，可以按如下方式访问
* ndarray.ndim - 存储数组的数字维度。
* ndarray.shape - 存储数组的形状，元组中每一个数字都表示每个相应维度的长度。
* ndarray.size - 存储数组中的元素数

In [53]:
multi_dim_arr.ndim

2

In [54]:
multi_dim_arr.shape

(2, 3)

In [55]:
multi_dim_arr.size

6

## 数组数字运算
在本节中，您将看到 NumPy 允许您快速对一维和多维数组执行元素加法、减法、乘法和除法。使用每个 '+'、'-' 和 '*' 的数学符号执行作。回想一下，添加 Python 列表的工作方式与附加列表完全不同，因此会生成更长的列表，此外，Python 列表的减法和乘法不起作用。

In [56]:
arr_1 = np.array([2,4,6])
arr_2 = np.array([1,3,5])

# 加法运算
addition = arr_1 + arr_2
print(addition)

# 减法运算
subtraction = arr_1 - arr_2
print(subtraction)

# 乘法运算
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


## 将向量与标量相乘
假设您需要将英里转换为公里。为此，您可以使用到目前为止学到的 NumPy 数组函数。您可以通过在数组 （miles） 和单个数字 （转换率，即标量） 之间执行作来执行此作。由于 1 英里 = 1.6 公里，因此 NumPy 计算每个单元格内的每次乘法。

这个概念称为广播，它允许您专门对不同形状的数组执行作。
即列表中的每个元素乘以倍率

In [57]:
vector = np.array([1,2])
vector *1.6

array([1.6, 3.2])

## 索引和切片
索引允许从数组从选择特定元素，选择整行/整列或平面，就像你在将来的多维数组分配中看到的那样

## 索引
从给定数组中选择特定元素

In [58]:
a = ([1,2,3,4,5])
print(a[2])
print(a[0])

3
1


对于形状为n的多维数组，要为特定元素编制索引，必须输入n个索引，每个维度一个索引

In [59]:
# 在2-D 数组上的索引
# 这里使用了元组嵌套的方法，当然列表嵌套也可以
two_dim = np.array(([1,2,3],[4,5,6],[7,8,9]))

print(two_dim)
# 使用索引i、j，从二维数组中选择元素编号8
# 第三行，第二列，索引从0开始
print(two_dim[2][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8


## 切片
切片可以提供从数组中指定的元素的子列表。切片表示法指定start和end值，并将列表从start——end(不包括)复制下来

语法为：

`数组[开始：结束：步长]`

start默认值为0，end默认值为数组长度-1，step默认值为1

In [60]:
# 将数组a切片获得数组[2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [61]:
# 将数组a切片得到数组[3,4,5]
sliced_arr = a[:3]
print(sliced_arr)

[1, 2, 3]


In [62]:
# 将数组a切片得到数组[3,4,5]
sliced_arr = a[2:]
print(sliced_arr)

[3, 4, 5]


In [63]:
# 将数组a切片得到数组[1,3,5]
sliced_arr = a[::2]
print(sliced_arr)

[1, 3, 5]


## 解释a== a[:] ==a[::]
* a[:]，没有传入参数，按默认值来切片
* a[::] ,同样没有传入参数
* 不用思考a[:]的冒号是第几个

In [64]:
# 注意 a== a[:] ==a[::]
print(a == a[:] == a[::])

True


In [65]:
# 将二维数组切片得到前两行
print(two_dim)
sliced_arr_1 = two_dim[0:2]
sliced_arr_1

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
#类似地，切片 two_dim 数组以获取最后两行
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [67]:
# 注意，','前面单独冒号出现意味中切片所有行，取第二列
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


## 堆叠
堆叠是Numpy的一项功能，可增加数组的自定义。这意味着水平或者垂直连接两个或多个数组，这意味着它是沿着新轴完成。

* np.vstack()- 垂直堆叠
* np.hstack()- 水平堆叠
* np.hsplit()- 将数组拆分为几个较小的数组

f-string 是 Python 3.6 及以上版本引入的一种字符串格式化方式，在字符串前加上 f 或 F 前缀，就可以在字符串中使用花括号 {} 来包含表达式，Python 会在运行时将这些表达式的值替换到字符串中。

In [68]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [69]:
# 将数组垂直堆叠
ver_stack = np.vstack((a1,a2))
print(ver_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [70]:
# 将数组水平堆叠
horz_stack = np.hstack((a1,a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]
