# 线性方程组系统
欢迎来到课程1的第一个作业。学习了线性方程组及其通过行化简求解的方法
**在此任务过后，您将能够:**
* 使用`numpy`包设置与线性方程做对应的数组
* 评估矩阵的行列式并使用`numpy`线性代数包求解系统
* 执行行简化以将矩阵转化为行阶梯形
* 求解线性方程组的解

# 导包

In [1]:
import numpy as np

加载为此笔记本定义的特定单元测试

In [3]:
import w2_unittest

# 线性方程组和相应的`Numpy`数组
矩阵可以用来解方程组。但首先，需要用矩阵表示该方程组。给定以下线性方程组：
$$\begin{cases} 
2x_1-x_2+x_3+x_4=6, \\ x_1+2x_2-x_3-x_4=3, \\ -x_1+2x_2+2x_3+2x_4=14, \\ x_1-x_2+2x_3+x_4=8, \end{cases}\tag{1}$$
构造矩阵`A`,其中每一行代表系统的一个方程，每一列代表变量`x1,x2,x3,x4`。从方程右侧的自由系数放入向量`b`中

## 练习1
构建与线性方程组$(1)$对应的矩阵`A`和向量$b$

In [9]:
A = np.array([
    [2, -1, 1, 1],
    [1, 2, -1, -1],
    [-1, 2, 2, 2],
    [1, -1, 2, 1]    
],dtype=np.dtype(float))  
            
b = np.array([6,3,14,8],dtype=np.dtype(float))

In [13]:
# 测试解决
w2_unittest.test_matrix(A,b)

 All tests passed


## 使用`numpy`线性代数包的方程组求解方案
一个含有四个未知变量的四个线性方程组，当且仅当其系数矩阵的行列式不等于零时，才有唯一解。`Numpy`提供了快速可靠地计算方阵行列式以及解线性方程组的途径

## 练习2
找到矩阵$A$的行列式$d$和线性方程组(1)的解向量x。

In [12]:
# 矩阵A的行列式
d = np.linalg.det(A)

# 求矩阵的解
x = np.linalg.solve(A,b)

print(f"矩阵A的行列式：{d:.2f}")
print(f"矩阵的解:{x}")

矩阵A的行列式：-17.00
矩阵的解:[2. 3. 4. 1.]


In [14]:
# 测试解答
w2_unittest.test_det_and_solution_scipy(d,x)

 All tests passed


## 基本运算和行简化操作
尽管当代软件包允许用一行代码找到解决方案，但手动执行所需的代数运算有助于建立对机器学习算法深入理解的必要基础。

这里将使用行简化法代数地解决线性方程组。这涉及到使用出等运算组合方程，尽可能多地消除每个方程中的变量。有三种有效操作可以将方程组转换为等价形式（具有相同的解）
* 将任意行乘以非零数
* 将两行相加，并将原始行中的一行与结果交换
* 交换行

## 练习3
设置三个函数，分别对应上述的基本操作。

In [21]:
def MultiplyRow(M,row_num,row_num_multiple):
    # 创建副本
    M_new = M.copy()
    # 将某行乘倍数并替换掉原来的那行
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new
def  AddRows(M,row_num_1,row_num_2,row_num_1_multiple):
    M_new = M.copy()
    # 某行乘以倍数加到另外一行上并交换原行
    M_new[row_num_2] = M_new[row_num_1] * row_num_1_multiple + M_new[row_num_2]
    return M_new
def SwapRows(M,row_num_1,row_num_2):
    M_new = M.copy()
    # 交换两行
    M_new[[row_num_1,row_num_2]] = M_new[[row_num_2,row_num_1]]
    return M_new


In [22]:
A_test = np.array([
        [1, -2, 3, -4],
        [-5, 6, -7, 8],
        [-4, 3, -2, 1], 
        [8, -7, 6, -5]
    ], dtype=np.dtype(float))
print("Original matrix:")
print(A_test)

print("\nOriginal matrix after its third row is multiplied by -2:")
print(MultiplyRow(A_test,2,-2))

print("\nOriginal matrix after exchange of the third row with the sum of itself and first row multiplied by 4:")
print(AddRows(A_test,0,2,4))

print("\nOriginal matrix after exchange of its first and third rows:")
print(SwapRows(A_test,0,2))

Original matrix:
[[ 1. -2.  3. -4.]
 [-5.  6. -7.  8.]
 [-4.  3. -2.  1.]
 [ 8. -7.  6. -5.]]

Original matrix after its third row is multiplied by -2:
[[ 1. -2.  3. -4.]
 [-5.  6. -7.  8.]
 [ 8. -6.  4. -2.]
 [ 8. -7.  6. -5.]]

Original matrix after exchange of the third row with the sum of itself and first row multiplied by 4:
[[  1.  -2.   3.  -4.]
 [ -5.   6.  -7.   8.]
 [  0.  -5.  10. -15.]
 [  8.  -7.   6.  -5.]]

Original matrix after exchange of its first and third rows:
[[-4.  3. -2.  1.]
 [-5.  6. -7.  8.]
 [ 1. -2.  3. -4.]
 [ 8. -7.  6. -5.]]


In [24]:
# 测试解答
w2_unittest.test_elementary_operations(MultiplyRow,AddRows,SwapRows)

 All tests passed
