# 求解线性方程组：3个变量
在这个实验室中，你将继续使用`Pthon`开发你的技能，以解决线性方程组。
* 使用`Numpy`线性代数包求解线性方程组的解
* 执行行简化以将矩阵转换为行阶梯形
* 求解线性方程组的解
* 评估矩阵的行列式，再次看到矩阵的奇异性与线性系统解的数量联系

# 导包

In [2]:
import numpy as np

# 使用矩阵表示和求解线性方程组

### 线性方程组系统
这是一个包含三个方程和三个未知变量的线性方程组
$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

要解这个线性方程组，就是要找到x1，x2，x3的值，使得所有方程同时满足。

## 使用矩阵求解线性方程组
让我们准备使用`Numpy`解决线性系统(1)。`A`将是一个矩阵，每一行将代表系统中的一个方程，每一列将对应变量x1、x2、x3。b是常量系数的1-D数组：

In [3]:
A = np.array([
    [4,-3,1],
    [2,1,3],
    [-1,2,-5]
],dtype = np.dtype(float))

b = np.array([-10,0,17],dtype=np.dtype(float))

print("矩阵A：")
print(A)
print("列表b：")
print(b)

矩阵A：
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
列表b：
[-10.   0.  17.]


检查$A$和$b$的尺寸，使用`shape()`函数

In [5]:
print(f"A的形状是：{np.shape(A)}")
print(f"b的形状是：{np.shape(b)}")

A的形状是：(3, 3)
b的形状是：(3,)


现在使用`np.linalg.solve(A,b)`函数求解系统（1）的解。结果保存在1-D数组x中。元素将对应于x1、x2和x3的值

In [9]:
x = np.linalg.solve(A,b)

print(f"矩阵的解{x}")

矩阵的解[ 1.  4. -2.]


## 矩阵行列式的评估
矩阵`A`对于线性系统（1）是一个方阵，它有相同的行和列。在方阵的情况下，可以计算其行列式 - 一个描述矩阵某些特性的实数。包含三个方程和三个未知变量的线性系统，当且仅当矩阵`A`的行列式非零时，才又一个解。

让我们使用`np.linalg.det(A)`函数计算行列式

In [10]:
d = np.linalg.det(A)

print(f"矩阵A的行列式是：{d:.2f}")

矩阵A的行列式是：-60.00


请注意，其值非零，正如预期那样

## 使用行简化法求解1线性方程组
### 行简化准备
可以看到使用现代软件包解决线性方程有多简单。然而，为了更深入理解数学概念，手动练习一些解题技巧是很重要的。编程方法在这里仍然可以帮助减少算数计算的数量，并专注于方法本身。

这里可以练习三变量线性方程组的行简化方法。要应用它，首先，使用`np.hstack()`函数将矩阵$A$和数组$b$合并成一个矩阵。注意，最初定义的数组$b$的形状是(3,),为了与(3,3)矩阵堆叠，需要将其转换成具有相同维数的形状，使用`.reshape((3,1))`函数：

In [11]:
A_system = np.hstack((A,b.reshape((3,1))))

print(A_system)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


## 基本操作函数
让我回顾基本运算，这些运算不会改变线性方程组的解集：
* 将任意行乘以非零数
* 将两行相加并与某一原始行交换
* 交换行

在较大系统的情况下，需要多次应用基本操作。因此，定义相应的Python函数是方便的

In [15]:
def MultiplyRow(M,row_num,row_num_multiple):
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

print("原矩阵是")
print(A_system)
print("矩阵在第三行乘以2后")
print(MultiplyRow(A_system,2,2))

原矩阵是
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]
矩阵在第三行乘以2后
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -2.   4. -10.  34.]]


In [17]:
def AddRows(M,row_num_1,row_num_2,num_row_multiple):
    M_new = M.copy()
    M_new[row_num_2] = M_new[row_num_1] * num_row_multiple + M_new[row_num_2]
    return M_new
print("原矩阵是")
print(A_system)
print("矩阵在将第一行乘以1/2再加到第二行上后")
print(AddRows(A_system,1,2,1/2))

原矩阵是
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]
矩阵在将第一行乘以1/2再加到第二行上后
[[  4.   -3.    1.  -10. ]
 [  2.    1.    3.    0. ]
 [  0.    2.5  -3.5  17. ]]


In [19]:
def SwapRows(M,num_row_1,num_row_2):
    M_new = M.copy()
    M_new[[num_row_1,num_row_2]] = M_new[[num_row_2,num_row_1]]
    return M_new

print("原矩阵是")
print(A_system)
print("将第一行和第三行进行交换后")
print(SwapRows(A_system,0,2))

原矩阵是
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]
将第一行和第三行进行交换后
[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


## 行简化与线性方程组的求解
现在您可以使用定义的操作将矩阵转换为行简化形式。要手动进行，在第一行的第一个元素中具有1或-1值是方便的。在Python中进行计算不会提供太多好处。但为了说明目的，这样做更好。因此，让我们交换第一行和第三行：

In [20]:
A_ref = SwapRows(A_system,0,2)

print(A_ref)

[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


现在你需要进行这样的基本操作，使得第二行和第三行的第一个元素等于零：

In [21]:
A_ref = AddRows(A_ref,0,1,2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  4.  -3.   1. -10.]]


In [22]:
A_ref = AddRows(A_ref,0,2,4)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   5. -19.  58.]]


In [23]:
A_ref = AddRows(A_ref,1,2,-1)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   0. -12.  24.]]


现在很容易找到第三行中x3的值，因为它对应于方程-12*x3=24.让我们将这一行除以-12:

In [24]:
A_ref = MultiplyRow(A_ref,2,-1/12)
print(A_ref)

[[-1.  2. -5. 17.]
 [ 0.  5. -7. 34.]
 [-0. -0.  1. -2.]]


现在矩阵的第二行对应于方程5*x2-7*x3 = 34，第一行对应于方程-x1+2*x2-5*x3 = 17。通过参考矩阵的元素，您可以找到x2和x1的值

In [28]:
x_3 = -2
x_2 = (A_ref[1,3]-A_ref[1,2] * x_3) / A_ref[1,1]
x_1 = (A_ref[0,3]-A_ref[0,2] * x_3 - A_ref[0,1] * x_2)/ A_ref[0,0]

print(x_1,x_2,x_3)

1.0 4.0 -2


## 无解的线性方程组
给定另一个线性方程组：
$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=0, \end{cases}\tag{2}$$
让我们找到相应矩阵的行列式。

In [29]:
A_2 = np.array([
    [1,1,1],
    [0,1,-3],
    [2,1,5],
],dtype=np.dtype(float))

b_2 = np.array([2,1,0],dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)
print(f"矩阵A_2的行列式的值为{d_2}")

矩阵A_2的行列式的值为0.0


它等于零，因此系统不能有一个唯一解。它将有无穷多个解或者没有解。其一致性将取决于自由系数(右侧系数)。
可以在下面单元中取消注释并运行代码，以姜茶`np.linalg.solve()`函数会因为奇异性而给出错误。

In [31]:
# x_2 = np.linalg.solve(A_2,b_2)

可以执行基本操作查看方程组没有解：

In [32]:
A_2_system = np.hstack((A_2,b_2.reshape((3,1))))
print(A_2_system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  0.]]


In [33]:
A_2_ref = AddRows(A_2_system,0,2,-2)
print(A_2_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -4.]]


In [34]:
A_2_ref = AddRows(A_2_ref,1,2,1)
print(A_2_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0. -3.]]


最后一行对应于方程0 = -3，该方程无解。因此，整个线性方程组(2)无解。

# 无穷多解的线性方程组
可以通过仅改变常量系数来将系统(2)带到一致性
$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=3. \end{cases}\tag{3}$$

定义新的常量系数数组：

In [35]:
b_3 = np.array([2,1,3])

准备对应于系统(3)的新矩阵

In [36]:
A_3_system = np.hstack(((A_2,b_3.reshape(3,1))))
print(A_3_system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  3.]]


In [37]:
A_3_ref = AddRows(A_3_system,0,2,-2)
print(A_3_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -1.]]


In [38]:
A_3_ref = AddRows(A_3_ref,1,2,1)
print(A_3_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0.  0.]]


因此从相应的线性系统中
$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 0=0, \end{cases}\tag{4}$$
你可以找到x2 = 1 + 3* x3，将其带入第一个方程中，并找到x1。因此，线性系统（3）的解为：
x3 是任意实数

记住，如果不存在或存在无限多个解，`np.linalg.solve`会报错，因此在实现它时，必须仔细思考，以免程序崩溃